import { jsPDF } from 'jspdf';
import { HackathonIdea } from '../types';

export const downloadIdeaAsPDF = (idea: HackathonIdea) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 30;

  // Background Color (Subtle)
  doc.setFillColor(250, 250, 252);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F');

  // Header Section
  doc.setFillColor(79, 70, 229); // Indigo-600
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('IDEAFORGE AI', margin, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('HACKATHON STRATEGIC BLUEPRINT', margin, 25);

  // Score Badge
  const score = idea.winningPotential.score;
  doc.setFillColor(16, 185, 129); // Emerald-500
  doc.roundedRect(pageWidth - margin - 35, 12, 35, 16, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`${score}`, pageWidth - margin - 17.5, 21, { align: 'center' });
  doc.setFontSize(8);
  doc.text('WINNING SCORE', pageWidth - margin - 17.5, 25, { align: 'center' });

  yPos = 55;

  // Project Title
  doc.setTextColor(17, 24, 39); // Gray-900
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(idea.projectTitle, pageWidth - (margin * 2));
  doc.text(titleLines, margin, yPos);
  yPos += (titleLines.length * 10) + 5;

  // One-line Pitch
  doc.setTextColor(107, 114, 128); // Gray-500
  doc.setFontSize(14);
  doc.setFont('helvetica', 'italic');
  const pitchLines = doc.splitTextToSize(`"${idea.oneLinePitch}"`, pageWidth - (margin * 2));
  doc.text(pitchLines, margin, yPos);
  yPos += (pitchLines.length * 7) + 15;

  // Problem Statement
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('PROBLEM STATEMENT', margin, yPos);
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(55, 65, 81); // Gray-700
  const problemLines = doc.splitTextToSize(idea.problemStatement, pageWidth - (margin * 2));
  doc.text(problemLines, margin, yPos);
  yPos += (problemLines.length * 6) + 15;

  // Key Features
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('CORE FEATURES', margin, yPos);
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(55, 65, 81);
  idea.coreFeatures.forEach((feature) => {
    const featureLines = doc.splitTextToSize(`• ${feature}`, pageWidth - (margin * 2) - 5);
    doc.text(featureLines, margin + 5, yPos);
    yPos += (featureLines.length * 6);
  });
  yPos += 10;

  // Tech Stack
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('TECHNICAL ARCHITECTURE', margin, yPos);
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(55, 65, 81);
  
  const techStack = [
    { label: 'Frontend', value: idea.technicalArchitecture.frontend },
    { label: 'Backend', value: idea.technicalArchitecture.backend },
    { label: 'APIs', value: idea.technicalArchitecture.apis },
    { label: 'Database', value: idea.technicalArchitecture.database },
  ];

  techStack.forEach((tech) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${tech.label}:`, margin, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(tech.value, margin + 25, yPos);
    yPos += 6;
  });

  yPos += 15;

  // Gemini Usage
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('GEMINI AI INTEGRATION', margin, yPos);
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(55, 65, 81);
  const geminiLines = doc.splitTextToSize(idea.geminiUsage, pageWidth - (margin * 2));
  doc.text(geminiLines, margin, yPos);
  yPos += (geminiLines.length * 6) + 15;

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175); // Gray-400
  doc.text('Generated by IdeaForge AI - Your Hackathon Strategist', pageWidth / 2, pageHeight - 10, { align: 'center' });

  doc.save(`${idea.projectTitle.replace(/\s+/g, '_')}_Blueprint.pdf`);
};
