import React, { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { useNavigate } from 'react-router-dom';
import { Code2, Target, Sparkles, ArrowRight, Brain, Zap, Rocket, Star, Download } from 'lucide-react';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { CursorTrail } from '../components/CursorTrail';
import { HackathonIdea } from '../types';
import { downloadIdeaAsPDF } from '../services/pdfService';

export const Showcase: React.FC = () => {
  const [ideas, setIdeas] = useState<HackathonIdea[]>([]);
  const navigate = useNavigate();

  useEffect(() => {
    const savedIdeas = localStorage.getItem('generated_ideas');
    if (savedIdeas) {
      try {
        setIdeas(JSON.parse(savedIdeas));
      } catch (e) {
        console.error('Failed to parse ideas', e);
      }
    }
  }, []);

  return (
    <div className="min-h-screen bg-[#030014] text-white font-sans selection:bg-purple-500/30 relative overflow-hidden">
      <CursorTrail />
      
      {/* Animated Background Blobs */}
      <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-purple-600/10 rounded-full blur-[120px] animate-blob" />
        <div className="absolute top-[20%] right-[-10%] w-[40%] h-[40%] bg-blue-600/10 rounded-full blur-[120px] animate-blob animation-delay-2000" />
        <div className="absolute bottom-[-10%] left-[20%] w-[45%] h-[45%] bg-pink-600/10 rounded-full blur-[120px] animate-blob animation-delay-4000" />
      </div>

      <Navbar />

      <main className="max-w-7xl mx-auto px-6 pt-40 pb-24 relative z-10">
        <div className="max-w-3xl mb-20">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="inline-flex items-center gap-2 px-3 py-1 bg-white/5 border border-white/10 text-white/40 rounded-full text-[9px] font-bold uppercase tracking-[0.2em] mb-6 backdrop-blur-sm"
          >
            <div className="w-1 h-1 rounded-full bg-purple-500 animate-pulse" />
            Archive
          </motion.div>
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-5xl lg:text-6xl font-bold tracking-tight text-white mb-6 leading-[1.1]"
          >
            Generated <span className="text-white/40">Ideas Showcase</span>
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-lg text-white/60 leading-relaxed max-w-2xl"
          >
            A curated collection of real-time architectures and winning concepts generated by IdeaForge AI. These are live blueprints for your next big build.
          </motion.p>
        </div>

        {ideas.length === 0 ? (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-center py-24 glass-card rounded-[40px] border border-dashed border-white/10"
          >
            <Brain className="w-16 h-16 text-white/10 mx-auto mb-6" />
            <h3 className="text-2xl font-bold text-white/40 mb-2">No ideas generated yet</h3>
            <p className="text-white/20 mb-8">Head back to the home page and architect your first winning project.</p>
            <a 
              href="/" 
              className="inline-flex items-center gap-2 px-8 py-3 bg-white/5 border border-white/10 rounded-full text-sm font-bold hover:bg-white/10 transition-all"
            >
              Start Generating <ArrowRight className="w-4 h-4" />
            </a>
          </motion.div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {ideas.map((idea, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                whileHover={{ y: -10, scale: 1.02 }}
                onClick={() => navigate(`/blueprint/${i}`)}
                className="glass-card p-8 rounded-[40px] border border-white/10 hover:border-purple-500/30 transition-all group relative overflow-hidden flex flex-col h-full cursor-pointer"
              >
                {/* Card Background Glow */}
                <div className={`absolute -top-24 -right-24 w-48 h-48 bg-gradient-to-br from-indigo-500 to-purple-500 opacity-0 group-hover:opacity-20 blur-[60px] transition-opacity duration-500`} />
                
                <div className="relative z-10 flex flex-col h-full">
                  <div className="flex justify-between items-start mb-8">
                    <div className="w-12 h-12 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform">
                      <Rocket className="w-6 h-6 text-purple-400" />
                    </div>
                    {idea.winningPotential?.score && (
                      <div className="px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 rounded-full flex items-center gap-1.5">
                        <Star className="w-3 h-3 text-emerald-400 fill-emerald-400" />
                        <span className="text-[10px] font-bold text-emerald-400">{idea.winningPotential.score}</span>
                      </div>
                    )}
                  </div>
                  
                  <h3 className="text-2xl font-bold text-white mb-3 tracking-tight group-hover:text-glow transition-all line-clamp-2">
                    {idea.projectTitle}
                  </h3>
                  
                  <p className="text-white/60 text-sm font-medium leading-relaxed mb-6 italic">
                    "{idea.oneLinePitch}"
                  </p>

                  <div className="space-y-3 mb-8 flex-grow">
                    <h4 className="text-[10px] font-bold uppercase tracking-widest text-white/30 flex items-center gap-2">
                      <Target className="w-3 h-3" /> Key Features
                    </h4>
                    <ul className="space-y-2">
                      {idea.coreFeatures.slice(0, 3).map((feature, j) => (
                        <li key={j} className="text-xs text-white/50 flex items-start gap-2">
                          <div className="mt-1.5 w-1 h-1 rounded-full bg-purple-500 shrink-0" />
                          <span className="line-clamp-2">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  
                  <div className="pt-6 border-t border-white/5 flex items-center justify-between">
                    <div className="flex -space-x-2">
                      {['React', 'Node', 'AI'].map((t, j) => (
                        <div key={j} className="w-6 h-6 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-[8px] font-bold text-white/40 backdrop-blur-sm">
                          {t[0]}
                        </div>
                      ))}
                    </div>
                    <div className="flex items-center gap-4">
                      <button 
                        onClick={(e) => {
                          e.stopPropagation();
                          downloadIdeaAsPDF(idea);
                        }}
                        className="p-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-white/40 hover:text-white transition-all group/btn"
                        title="Download as PDF"
                      >
                        <Download className="w-4 h-4 group-hover/btn:scale-110 transition-transform" />
                      </button>
                      <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-white/40 group-hover:text-white transition-colors">
                        View Blueprint
                        <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" />
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </main>

      <Footer />
    </div>
  );
};
